"""Geospatial foundation: admin hierarchy, slope units, terrain, infrastructure.

Revision ID: 0001_geo_foundation
Revises:
Created: 2026-09-09

Written by hand rather than autogenerated, because autogenerate needs a live
database and the extension bootstrap below has to run before any table that
uses a geometry column.

Index strategy, per the Phase 1 brief:
  - GIST on every geometry column. These are declared explicitly because the
    models set spatial_index=False, so there is exactly one place where spatial
    indexes are defined.
  - BRIN on time columns of the append-mostly tables. BRIN is a few kilobytes
    against a B-tree's hundreds of megabytes, and rows written in time order
    are physically clustered, which is the case that BRIN is built for.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_geo_foundation"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SRID = 4326

# Columns shared by every level of the administrative hierarchy.
def _admin_columns() -> list[sa.Column]:
    return [
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("name_local", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("code", sa.String(32)),
        sa.Column("area_km2", sa.Float()),
        sa.Column("population", sa.Integer()),
        sa.Column("households", sa.Integer()),
        # Defaults to true: geometry is treated as unofficial unless a loader
        # explicitly says otherwise.
        sa.Column("provisional", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("attributes", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    ]


def _multipolygon(nullable: bool = False) -> sa.Column:
    return sa.Column(
        "geom",
        geoalchemy2.Geometry("MULTIPOLYGON", srid=SRID, spatial_index=False),
        nullable=nullable,
    )


def upgrade() -> None:
    # The compose stack creates these in infra/postgres/init. Repeating them
    # here means a migration run against any empty database succeeds, including
    # a managed instance where the init scripts never ran.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ---------------------------------------------------------------- state
    op.create_table("state", *_admin_columns(), _multipolygon())
    op.create_index("ix_state_name", "state", ["name"])
    op.create_index("ix_state_code", "state", ["code"])
    op.create_index("ix_state_geom", "state", ["geom"], postgresql_using="gist")

    # ------------------------------------------------------------- district
    op.create_table(
        "district",
        *_admin_columns(),
        sa.Column("state_id", postgresql.UUID(as_uuid=True), nullable=False),
        _multipolygon(),
        sa.ForeignKeyConstraint(["state_id"], ["state.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_district_name", "district", ["name"])
    op.create_index("ix_district_code", "district", ["code"])
    op.create_index("ix_district_state_id", "district", ["state_id"])
    op.create_index("ix_district_geom", "district", ["geom"], postgresql_using="gist")

    # ---------------------------------------------------------------- block
    op.create_table(
        "block",
        *_admin_columns(),
        sa.Column("district_id", postgresql.UUID(as_uuid=True), nullable=False),
        _multipolygon(),
        sa.ForeignKeyConstraint(["district_id"], ["district.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_block_name", "block", ["name"])
    op.create_index("ix_block_code", "block", ["code"])
    op.create_index("ix_block_district_id", "block", ["district_id"])
    op.create_index("ix_block_geom", "block", ["geom"], postgresql_using="gist")

    # -------------------------------------------------------------- village
    op.create_table(
        "village",
        *_admin_columns(),
        sa.Column("block_id", postgresql.UUID(as_uuid=True)),
        sa.Column("district_id", postgresql.UUID(as_uuid=True), nullable=False),
        # Nullable: many settlements are known only as a point.
        _multipolygon(nullable=True),
        sa.Column(
            "centroid",
            geoalchemy2.Geometry("POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("population_children", sa.Integer()),
        sa.Column("population_elderly", sa.Integer()),
        sa.Column("population_disabled", sa.Integer()),
        sa.Column("pin_code", sa.String(10)),
        sa.Column("notes", sa.Text()),
        sa.ForeignKeyConstraint(["block_id"], ["block.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_id"], ["district.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_village_name", "village", ["name"])
    op.create_index("ix_village_code", "village", ["code"])
    op.create_index("ix_village_district_id", "village", ["district_id"])
    op.create_index("ix_village_pin_code", "village", ["pin_code"])
    op.create_index("ix_village_geom", "village", ["geom"], postgresql_using="gist")
    op.create_index("ix_village_centroid", "village", ["centroid"], postgresql_using="gist")

    # The command palette must find a village by a partial or misspelt name, so
    # trigram search backs it rather than a LIKE scan over every settlement.
    op.execute("CREATE INDEX ix_village_name_trgm ON village USING gin (name gin_trgm_ops)")

    # ----------------------------------------------------------- slope_unit
    op.create_table(
        "slope_unit",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "geom",
            geoalchemy2.Geometry("POLYGON", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.Geometry("POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("hillslope_id", sa.Integer(), nullable=False),
        sa.Column("basin_id", sa.Integer()),
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("district_id", postgresql.UUID(as_uuid=True)),
        sa.Column("village_id", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["district_id"], ["district.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["village_id"], ["village.id"], ondelete="SET NULL"),
        # A hillslope identifier is unique within a delineation run. This is
        # what makes the pipeline idempotent: re-running a run upserts rather
        # than duplicating every unit in the region.
        sa.UniqueConstraint("run_id", "hillslope_id", name="uq_slope_unit_run_hillslope"),
    )
    op.create_index("ix_slope_unit_run_id", "slope_unit", ["run_id"])
    op.create_index("ix_slope_unit_district_id", "slope_unit", ["district_id"])
    op.create_index("ix_slope_unit_run_district", "slope_unit", ["run_id", "district_id"])
    op.create_index("ix_slope_unit_geom", "slope_unit", ["geom"], postgresql_using="gist")
    op.create_index("ix_slope_unit_centroid", "slope_unit", ["centroid"], postgresql_using="gist")
    op.create_index(
        "ix_slope_unit_created_at_brin",
        "slope_unit",
        ["created_at"],
        postgresql_using="brin",
    )

    # ------------------------------------------------------- terrain_profile
    op.create_table(
        "terrain_profile",
        sa.Column("slope_unit_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("elevation_min_m", sa.Float()),
        sa.Column("elevation_mean_m", sa.Float()),
        sa.Column("elevation_max_m", sa.Float()),
        sa.Column("local_relief_m", sa.Float()),
        sa.Column("slope_deg", sa.Float()),
        sa.Column("slope_max_deg", sa.Float()),
        sa.Column("slope_std_deg", sa.Float()),
        sa.Column("aspect_deg", sa.Float()),
        sa.Column("plan_curvature", sa.Float()),
        sa.Column("profile_curvature", sa.Float()),
        sa.Column("twi", sa.Float()),
        sa.Column("tpi", sa.Float()),
        sa.Column("flow_accumulation", sa.Float()),
        sa.Column("distance_to_stream_m", sa.Float()),
        sa.Column("distance_to_road_m", sa.Float()),
        sa.Column("distance_to_fault_m", sa.Float()),
        sa.Column("land_cover_class", sa.SmallInteger()),
        sa.Column("lithology_class", sa.String(64)),
        sa.Column("soil_depth_m", sa.Float()),
        sa.Column("provenance", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["slope_unit_id"], ["slope_unit.id"], ondelete="CASCADE"),
        # A slope angle outside this range is a unit error or a corrupt raster,
        # not terrain. Catching it at write time is far cheaper than tracing a
        # nonsensical factor of safety back through the model later.
        sa.CheckConstraint(
            "slope_deg IS NULL OR (slope_deg >= 0 AND slope_deg <= 90)",
            name="slope_deg_within_range",
        ),
        sa.CheckConstraint(
            "aspect_deg IS NULL OR (aspect_deg >= 0 AND aspect_deg < 360)",
            name="aspect_deg_within_range",
        ),
        sa.CheckConstraint(
            "soil_depth_m IS NULL OR soil_depth_m > 0",
            name="soil_depth_positive",
        ),
    )
    op.create_index("ix_terrain_profile_lithology_class", "terrain_profile", ["lithology_class"])

    # --------------------------------------------------------- road_segment
    op.create_table(
        "road_segment",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("osm_id", sa.String(32)),
        sa.Column(
            "geom",
            geoalchemy2.Geometry("LINESTRING", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(200)),
        sa.Column("highway_class", sa.String(32), nullable=False),
        sa.Column("length_m", sa.Float(), nullable=False),
        sa.Column("is_bridge", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_tunnel", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("betweenness_centrality", sa.Float()),
        sa.Column("attributes", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_road_segment_osm_id", "road_segment", ["osm_id"])
    op.create_index("ix_road_segment_highway_class", "road_segment", ["highway_class"])
    op.create_index(
        "ix_road_segment_class_centrality",
        "road_segment",
        ["highway_class", "betweenness_centrality"],
    )
    op.create_index("ix_road_segment_geom", "road_segment", ["geom"], postgresql_using="gist")

    # ---------------------------------------------------- critical_facility
    op.create_table(
        "critical_facility",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("osm_id", sa.String(32)),
        sa.Column(
            "geom",
            geoalchemy2.Geometry("POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(200)),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("capacity", sa.Integer()),
        sa.Column("attributes", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_critical_facility_osm_id", "critical_facility", ["osm_id"])
    op.create_index("ix_critical_facility_category", "critical_facility", ["category"])
    op.create_index(
        "ix_critical_facility_geom", "critical_facility", ["geom"], postgresql_using="gist"
    )


def downgrade() -> None:
    # Reverse creation order so foreign keys never block a drop.
    op.drop_table("critical_facility")
    op.drop_table("road_segment")
    op.drop_table("terrain_profile")
    op.drop_table("slope_unit")
    op.execute("DROP INDEX IF EXISTS ix_village_name_trgm")
    op.drop_table("village")
    op.drop_table("block")
    op.drop_table("district")
    op.drop_table("state")
    # Extensions are deliberately left in place. Other databases on the same
    # instance may depend on them, and dropping PostGIS is never what a
    # rollback of one migration should do.
