import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import prettier from "eslint-config-prettier";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Flat config for ESLint 9 with eslint-config-next 15.
 *
 * The config generated by create-next-app imports
 * `eslint-config-next/core-web-vitals` as an ES module, which only exists in
 * eslint-config-next 16. This project pins Next 15 (see AGENTS.md), so the
 * shareable configs are loaded through FlatCompat instead.
 */
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [".next/**", "out/**", "build/**", "next-env.d.ts", "node_modules/**"],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // An unused variable in a warning system is usually a dropped value, not
      // dead code. Underscore-prefixed names are the explicit opt-out.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Must stay last so formatting rules never fight Prettier.
  prettier,
];

export default eslintConfig;
